jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        apt-get update
        apt-get install qemu-system-x86
        echo ":qemu-x86_64:M::\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x3e\x00:\xff\xff\xff\xff\xff\xfe\xfe\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/libexec/qemu-binfmt/x86_64-binfmt-P:P" | tee /proc/sys/fs/binfmt_misc/register
        cat /proc/$$/comm
